# Generated by Django 4.1.5 on 2024-05-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0002_alter_customer_sex_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
    ]
