# Generated by Django 4.1.5 on 2024-05-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0003_remove_customer_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zip_code',
        ),
    ]
