# Generated by Django 4.1.5 on 2024-05-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0005_customer_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.CharField(default='25', max_length=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Feminine')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(max_length=16),
        ),
    ]
