# Generated by Django 4.1.5 on 2024-05-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0006_customer_age_customer_sex_alter_customer_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.CharField(default=' ', max_length=12),
        ),
    ]
