# Generated by Django 4.1.5 on 2024-05-17 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0007_alter_customer_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sex',
        ),
    ]
