# Generated by Django 4.1.5 on 2024-05-20 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0009_customer_age_customer_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fact_app.customer'),
        ),
    ]
