# Generated by Django 4.1.5 on 2024-05-20 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fact_app', '0010_alter_invoice_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='save_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
