# Generated by Django 4.1.5 on 2024-05-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0012_article_prix_vente_article_remise_article_tva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='prix_vente',
            field=models.DecimalField(decimal_places=3, max_digits=1000),
        ),
    ]
