# Generated by Django 4.1.5 on 2024-05-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0013_alter_article_prix_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='prix_vente',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=1000),
        ),
    ]
