# Generated by Django 4.1.5 on 2024-05-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0014_alter_article_prix_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='montant_ht',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix_vente',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='total',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=1000),
        ),
    ]
