# Generated by Django 4.1.5 on 2024-05-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0016_alter_article_montant_ht_alter_article_montant_ttc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
