# Generated by Django 4.1.5 on 2024-05-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0017_invoice_montant_ht_invoice_montant_ttc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='montant_ht',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
