# Generated by Django 4.1.5 on 2024-05-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0018_alter_invoice_montant_ht_alter_invoice_montant_ttc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('R', 'Receipt'), ('P', 'Proforma Invoice'), ('I', 'Invoice')], max_length=1),
        ),
    ]
