# Generated by Django 4.1.5 on 2024-05-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0019_alter_customer_sex_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Feminine')], default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('R', 'RECEIPT'), ('P', 'PROFORMA INVOICE'), ('I', 'INVOICE')], max_length=1),
        ),
    ]
