# Generated by Django 4.1.5 on 2024-05-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0020_alter_customer_sex_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='montant_ht',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
