# Generated by Django 4.1.5 on 2024-05-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0021_alter_article_montant_ht_alter_article_montant_ttc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='montant_ht',
            field=models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=10),
        ),
    ]
