# Generated by Django 4.1.5 on 2024-05-25 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0024_alter_customer_save_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sex',
        ),
    ]
