# Generated by Django 4.1.5 on 2024-05-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0025_remove_customer_age_remove_customer_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=132, unique=True),
        ),
    ]
