# Generated by Django 4.1.5 on 2024-05-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0028_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='code',
            field=models.CharField(default='DEFAULT_CODE', max_length=32),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=132),
        ),
    ]
