# Generated by Django 4.1.5 on 2024-05-29 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0031_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='name_c',
        ),
    ]
