# Generated by Django 4.1.5 on 2024-05-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0032_rename_name_article_name_c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name_c',
            new_name='name',
        ),
    ]
