# Generated by Django 4.1.5 on 2024-05-31 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0033_rename_name_c_article_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='total',
        ),
    ]
