# Generated by Django 4.1.5 on 2024-06-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0035_article_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='last_updated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
