# Generated by Django 4.1.5 on 2024-06-05 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0039_alter_customer_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fact_app.invoice'),
        ),
    ]
