# Generated by Django 4.1.5 on 2024-06-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0042_alter_article1_options_rename_code1_article1_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article1',
        ),
    ]
