# Generated by Django 4.1.5 on 2024-06-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0043_delete_article1'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='prix_vente',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
