# Generated by Django 4.1.5 on 2024-06-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0044_invoice_prix_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
