# Generated by Django 4.1.5 on 2024-06-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0045_alter_article_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='prix',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
