# Generated by Django 4.1.5 on 2024-09-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0046_article_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='prix_vente',
        ),
    ]
